development:
  vkontakte_app_id: 6763053
  vkontakte_app_secret: 3xTygfWmo0PfCXMvusyl

  github_app_id: a24002fcfca51789281c
  github_app_secret: a3cf3f4ef74fac593077bb7b310df8a759754507

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"]
  vkontakte_app_id: <%= ENV["VKONTAKTE_APP_ID"]
  vkontakte_app_secret: <%= ENV["VKONTAKTE_APP_SECRET"]
  github_app_id: <%= ENV["GITHUB_APP_ID"]
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"]
